
default: &default
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bruno
  password: 

development:
  <<: *default
  database: book_api_development
  
test:
  <<: *default
  database: book_api_test
  
production:
  <<: *default
  database: book_api_production
  username: book_api
  password: <%= ENV['BOOK_API_DATABASE_PASSWORD'] %>